condense_wildcard_suffixes=true
format_code_in_doc_comments=true
format_macro_matchers=true
format_strings=true
imports_layout="Vertical"
match_arm_leading_pipes="Always"
match_block_trailing_comma=true
max_width=120
imports_granularity="One"
newline_style="Unix"
normalize_comments=true
normalize_doc_attributes=true
overflow_delimited_expr=true
reorder_impl_items=true
group_imports="One"
type_punctuation_density="Compressed"
use_field_init_shorthand=true
use_try_shorthand=true
where_single_line=true
wrap_comments=true
attr_fn_like_width=120
blank_lines_upper_bound=1
empty_item_single_line=true
force_multiline_blocks=true
format_generated_files=false
merge_derives=true
trailing_semicolon=true
trailing_comma="Vertical"

error_on_line_overflow=true
error_on_unformatted=true
